scripts: zfs-root-generator: write sysroot.mount to generator.early

diff --git a/zfs-root-generator b/zfs-root-generator
--- a/zfs-root-generator
+++ b/zfs-root-generator
@@ -30,15 +30,23 @@ enable_unit() {
 }
 
 write_unit() {
-	local unit="$1"
-	log "writing $unit"
+	local unit="$1" dest="$GENERATOR_DIR"
+
+	# HACK: we put sysroot.mount into generator.early/ to override
+	#       the sysroot.mount generated by systemd-fstab-generator 
+	if [[ "$unit" == sysroot.mount ]]; then
+		dest="$GENERATOR_EARLY_DIR"
+		log "writing $unit (working around systemd-fstab-generator)"
+	else
+		log "writing $unit"
+	fi
 	{
 		cat <<-"EOF"
 		# Automatically generated by zfs-root-generator
 
 		EOF
 		cat
-	} | install -Dm644 /dev/stdin "$GENERATOR_DIR/$unit"
+	} | install -Dm644 /dev/stdin "$dest/$unit"
 }
 
 write_common_units() {
@@ -110,6 +118,8 @@ write_mount_unit() {
 	local what="$1" where="$2" unit
 
 	unit="$(systemd-escape --path --suffix=mount "$where")"
+	# HACK: write_unit puts sysroot.mount into generator.early/
+	#       to override the sysroot.mount from systemd-fstab-generator
 	write_unit "$unit" <<-EOF
 	[Mount]
 	Type=zfs
@@ -121,7 +131,6 @@ write_mount_unit() {
 }
 
 write_sysroot_unit() {
-	# install -Dm644 /dev/stdin "$GENERATOR_DIR/sysroot.mount.d/zfs-override.conf"
 	write_mount_unit "\${ZFS_ROOT_DATASET}" "/sysroot"
 }
 
@@ -200,8 +209,16 @@ write_sysroot_recursive() {
 setup_debug
 
 GENERATOR_DIR="$1"
+GENERATOR_EARLY_DIR="$2"
+GENERATOR_LATE_DIR="$3"
 if ! [[ "$GENERATOR_DIR" && -d "$GENERATOR_DIR" ]]; then
 	die "invalid generator directory \"$GENERATOR_DIR\""
+fi
+if ! [[ "$GENERATOR_EARLY_DIR" && -d "$GENERATOR_EARLY_DIR" ]]; then
+	die "invalid early generator directory \"$GENERATOR_EARLY_DIR\""
+fi
+if ! [[ "$GENERATOR_LATE_DIR" && -d "$GENERATOR_LATE_DIR" ]]; then
+	die "invalid late generator directory \"$GENERATOR_LATE_DIR\""
 fi
 
 if vars_present; then
